name: Register images
on:
  workflow_dispatch:
    inputs:
      pattern:
        description: "Flow Name Pattern? (defaults to all)"
        required: false
        default: ".*"
jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find images/ -maxdepth 2 -mindepth 2 | grep "${{ github.event.inputs.pattern }}" | jq -Rsc '. / "\n" - [""]')"

  buildandpush:
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      matrix:
        flow-folder: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
      max-parallel: 10
    steps:
      - uses: actions/checkout@v2
      # Log in to azure cli using service principal
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Build and push image to azure container registry
      - name: ACR Login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
      - name: Build and push image
        working-directory: ${{ matrix.flow-folder }}
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ matrix.flow-folder }}:${{ github.sha }}
      